### ISSUE TITLE
Folder names and busybox compilation

### ISSUE THREAD

**Issue by jeffreyantony** [telmomarques/xiaomi-360-1080p-hacks#1]
Thanks for the code. I have few questions

1) Is there any reason to use the folder name "manu_test" and "x360h" ? Is it that the firmware looks for these folders inside the SD card ? If yes, how did you find it (reverse engineer the firmware) ?

2) How was the Busybox built - Which compiler and which settings did you use ? Did you compile it for ARM7 ?

**Comment by telmomarques** [comment]
Hi,

The folder "manu_test" is used by the firmware. The folder "x360h" is just short for "xiaomi 360 hacks"; the firmware doesn't look for this folder directly, but the manu.sh script looks for other scripts in here.

I've just added the ["How the hack works"](https://github.com/telmomarques/xiaomi-360-1080p-hacks/wiki/How-the-hack-works) page to the wiki, check it out for more details.

2.  Busybox was just downloaded from here: [https://busybox.net/downloads/binaries/](https://busybox.net/downloads/binaries/). There's binaries for multiple platforms, including arm7.
