### ISSUE TITLE
How to control camera via telnet?

### ISSUE THREAD

**Issue by funivan** [telmomarques/xiaomi-360-1080p-hacks#10]
Thanks for the hack. All works fine.  I downgrade the firmware and install this hack. Then successfully login via telnet.

Here is my question: how can I turn the camera to the right or left from the telnet? Or execute other commands, for example, enable sleep mode. Thanks.

**Comment by telmomarques** [comment]
Hi, unfortunately I didn't have time to look at that, yet.
There might be some way of accessing the GPIO directly, not sure.

**Comment by CleverNamesTaken** [comment]
I want to spend some more time looking at the GPIO, but uh... you can turn on and off the LED by controlling the content of /sys/class/gpio/gpio78/value
OFF
echo 0 > /sys/class/gpio/gpio78/value
ON
echo 1 > /sys/class/gpio/gpio78/value

I want to try to take a look at actually controlling the direction of the camera, but I need to find some time to investigate.

**Comment by telmomarques** [comment]
Nice work @CleverNamesTaken , thank you for the share!

**Comment by Jialn** [comment]
Thanks for the share. Is there any more progress now?

**Comment by telmomarques** [comment]
Duplicate of #21.
@Jialn please see that issue, someone has made progress.

**Comment by thewh1teagle** [comment]
> I want to spend some more time looking at the GPIO, but uh... you can turn on and off the LED by controlling the content of /sys/class/gpio/gpio78/value
> OFF
> echo 0 > /sys/class/gpio/gpio78/value
> ON
> echo 1 > /sys/class/gpio/gpio78/value
> 
> I want to try to take a look at actually controlling the direction of the camera, but I need to find some time to investigate.

Just want to update that you can control every led. 

for yellow led:

ON : 
```
echo 1 > /sys/class/gpio/gpio36
```
OFF:
 ```
echo 0 > /sys/class/gpio/gpio36
```


for blue led:

ON : 
```
echo 1 > /sys/class/gpio/gpio78
```
OFF:
 ```
echo 0 > /sys/class/gpio/gpio78
```
