### ISSUE TITLE
What can I do with telnet?

### ISSUE THREAD

**Issue by crearo** [telmomarques/xiaomi-360-1080p-hacks#11]
It might be helpful if I knew what I could with telnet. I'm planning on trying out what you've put in the readme but I'm not quite sure it'll get me anywhere.
All I want is to be able to receive a local rtsp stream over my router. Is that possible yet?

**Comment by telmomarques** [comment]
Hi @crearo,

RTSP streaming is still not available. Please use https://github.com/telmomarques/xiaomi-360-1080p-hacks/issues/2 to follow that development. Thank you.
