### ISSUE TITLE
Can xiaomi 360 camera work in US?

### ISSUE THREAD

**Issue by logicmd** [telmomarques/xiaomi-360-1080p-hacks#13]
Hi 

I am assuming we are talking about this(https://www.mi.com/camera-360/) in the repo. 

Heard some history about Yi camera restrict the camera usage outside China. Can xiaomi 360 camera work in United States?

Let me know if it is not the right place to post. 

Thanks

**Comment by telmomarques** [comment]
Hey,

That seems to be the one, yes.
I don't know about the USA specifically, but the camera is sold outside china, and I'm using it outside china also without any issues.

I don't think you need to worry about that, at least not with this camera.
