### ISSUE TITLE
Why not merging with mijia-720p-hack ?

### ISSUE THREAD

**Issue by BaQs** [telmomarques/xiaomi-360-1080p-hacks#14]
Hi there,

When trying to find out a suitable hack for my 1080p 360 camera, I found out that there is some (deleted?) tutorial using this hack:
https://github.com/ghoost82/mijia-720p-hack

The tutorial can be found here:
https://webcache.googleusercontent.com/search?q=cache:sWFK49TyDwMJ:https://geex.shop/guides/how-to-receive-rtsp-from-xiaomi-mijia-360-camera/

IMHO, most of the tools used in the 720p hack could be re-used here ?

Best

**Comment by telmomarques** [comment]
Hi,

Mijia 720p camera uses a different SoC (GM8136), unfortunately not compatible.
