### ISSUE TITLE
sdcard file structure

### ISSUE THREAD

**Issue by pickeld** [telmomarques/xiaomi-360-1080p-hacks#20]
Hey, i successfully downgraded the camera.
i copied both **folders** (hacks + menu_test) to the root of the sdcard. 
turn the camera on but cant reach the web
what am i missing?
thanks

**Comment by telmomarques** [comment]
Hey,

Can you please specify what do you mean by "reach the web"?

**Comment by pickeld** [comment]
thanks for the quick replay. im trying to get the camera on the <IP>:80.

**Comment by pickeld** [comment]
sorry, just realized i should telnet

**Comment by dr400** [comment]
telnet is sending back a "connection refused" ... port is 23

**Comment by thewh1teagle** [comment]
@dr400 
I think that telnet is not running in last version. Try ssh instead.

**Comment by dr400** [comment]
> @dr400
> I think that telnet is not running in last version. Try ssh instead.

you're right ! ssh is working great but not telnet ...

**Comment by telmomarques** [comment]
> > @dr400
> > I think that telnet is not running in last version. Try ssh instead.
> 
> you're right ! ssh is working great but not telnet ...

Telnet was replaced by SSH in the latest version.
