### ISSUE TITLE
Any way to control the motor?

### ISSUE THREAD

**Issue by Jialn** [telmomarques/xiaomi-360-1080p-hacks#21]
I have this product, and want to make a tele controlled robot by replacing the cable of original motor with DC motor driver pins on the robot. 
That might require controlling to the motor's GPIO (accessing the GPIO directly to skip low-level stepper motor drivers), anyway to do this?

**Comment by telmomarques** [comment]
Hi!

You can try asking on the telegram group (you can find the link in another issue), I think someone has posted something about controlling the motor, not 100% sure though.

Sorry for not being able to help more.

**Comment by Jialn** [comment]
Thanks for the quick replay! I'll check that.

**Comment by Jialn** [comment]
Sorry, any hint to which issue has the link of telegram group? Can not find it.

**Comment by telmomarques** [comment]
Sure, here it is: https://t.me/mijav4RTSP

**Comment by Jialn** [comment]
thanks

**Comment by thewh1teagle** [comment]
Hi 
I created repo for that thing, you can control the motor directly with my code. 
https://github.com/thewh1teagle/xiaomi-1080-360-motor-control
