### ISSUE TITLE
I have managed to un-brick my MJSXJ05CM  with https://drive.google.com/file/d/1ve6XlBEiZebJV6ukJ0Oiu7DePw2JCsWj/view

### ISSUE THREAD

**Issue by Shevbo** [telmomarques/xiaomi-360-1080p-hacks#26]
I have managed to un-brick my MJSXJ05CM  with https://drive.google.com/file/d/1ve6XlBEiZebJV6ukJ0Oiu7DePw2JCsWj/view

Any update on the hack?

_Originally posted by @Fruityski in https://github.com/telmomarques/xiaomi-360-1080p-hacks/issues/18#issuecomment-598550451_

absolutely the same - waiting for update for MJSXJ05CM to use RTSP!!!!

**Comment by jonathanhar** [comment]
Same here, waiting for the RTSP :)

**Comment by PauloDIas12** [comment]
Sorry. New in all this. I have a Mi Home Security Camera 360 1080p about two days.
I need to use it to mnonitor my baby. The Mi home app close in background and I need to keep it alive to hear the sound. What should I do?
Regards,

**Comment by kathgironpe** [comment]
> Sorry. New in all this. I have a Mi Home Security Camera 360 1080p about two days.
> I need to use it to mnonitor my baby. The Mi home app close in background and I need to keep it alive to hear the sound. What should I do?
> Regards,

You better read a lot before trying things, because some have bricked their cameras. This repo is only for this version: `MJSXJ02CM`.

**Comment by PauloDIas12** [comment]
> 
> 
> > Sorry. New in all this. I have a Mi Home Security Camera 360 1080p about two days.
> > I need to use it to mnonitor my baby. The Mi home app close in background and I need to keep it alive to hear the sound. What should I do?
> > Regards,
> 
> You better read a lot before trying things, because some have bricked their cameras. This repo is only for this version: `MJSXJ02CM`. I have read some who tried and got things to work for `MJSXJ05CM`.

Thanks

**Comment by dm800pvr** [comment]
Hey,
3.5.1_0052 downgrade is not possible for MJSXJ05CM !!!!
 I test several sd cards it just rename tf_recovery.img to tf_recovery.img.bak and create some folders!!
that's it! any solution?

**Comment by mathieuedet** [comment]
Hi, same problem, I bricked my cam by testing downgrade and tested with two micro sdcard (2 sandisk classe 10) : a 16Go / a 64Go. I have formatted sdcard to FAT32 format. I have tested about 10 img but still solid yellow led... Any solution ?
