### ISSUE TITLE
Complete Data track

### ISSUE THREAD

**Issue by AlessandroParolin** [telmomarques/xiaomi-360-1080p-hacks#29]
Hi, I'm new here but i want to help (at least try).
I usually check for rtsp packet or stuff like that, but here, i didnt find anything.

[MiHomeSecurityCamera360_1080p.zip](https://github.com/telmomarques/xiaomi-360-1080p-hacks/files/4611900/MiHomeSecurityCamera360_1080p.zip)

(the file is the scan of my ethernet port while opening the mi home app and loading the camera, meybe it can help)

**Comment by telmomarques** [comment]
Hi Alessandro!

We already have RTSP, but it's still in closed alpha testing. Will be releasing to the public in the next few days! I'm just putting the build workflows together to make a proper release.
