### ISSUE TITLE
Problem downgrade firmware

### ISSUE THREAD

**Issue by saipafo** [telmomarques/xiaomi-360-1080p-hacks#33]
Hello, i followed your instructions but i was unable to downgrade the firmware.
When I put the sdcard into the camera, the led is solid yellow. And nothing happen. I'm waiting for 1hour...

I try to power off, and remove the SDCard, but same, nothing happen. Now i can't power on the camera.

I have try an other SD card. Same issue :( .

Can help?

**Comment by telmomarques** [comment]
Hi,

Please confirm camera model on the bottom of the camera.

**Comment by saipafo** [comment]
Yes!

Model: MJSXJ05CM

**Comment by telmomarques** [comment]
Hey,

Check the supported camera model list on the repo readme 😋

See #18 how to unbrick your camera, join the discord server if you want more info: https://discord.gg/qggupzu
