### ISSUE TITLE
10min flashing ?

### ISSUE THREAD

**Issue by ysoudy** [telmomarques/xiaomi-360-1080p-hacks#35]
Hi,

I insert the SD CARD with he downgrade firmeware, and I m waiting since 10min.
It seems very long for a flash :(

What should I do ?

**Comment by ysoudy** [comment]
It's still on solid LED yellow

**Comment by kakemanx** [comment]
Are your camera the right one?
I did the same thing... flashed a mjsxj05cm and bricked it (can get it back thou :) )
The hacked firmware is for the

**Comment by ysoudy** [comment]
oops... my camera is Xiaomi Mi Home Security Camera 360
it's not the same ?

**Comment by ysoudy** [comment]
How can I unbrick it ?

**Comment by kakemanx** [comment]
> How can I unbrick it ?

Check the bottom of the camera and check that You have the 05 model, then download what i linked and flash it just like you did the other :)

**Comment by ysoudy** [comment]
It's a 05cm :(
SO i just turn OFF, put the new firmware you give me from google drive to the SD card, and turn on ?

Thx a lot !
