### ISSUE TITLE
Black screen Xiaomi Home after hack for MJSXJ02CM

### ISSUE THREAD

**Issue by xM1Stake** [telmomarques/xiaomi-360-1080p-hacks#40]
For camera MJSXJ02CM with  hack v1.1-rc1, I can see camera from the web, and control its via Xiaomi Home App, but on the app I receive black screen no video.

All other works fine.

Could someone help me to fix the issue?

Thanks in advance for any reply.

![IMG_1509](https://user-images.githubusercontent.com/49598041/84664101-55b49880-af1e-11ea-837d-c827e054ae91.PNG)

**Comment by olivr2s** [comment]
Is the RTSP configured in H265?
H264 -> black screen
H265 -> Video

**Comment by xM1Stake** [comment]
Hi olivr2s
no RTSP configure in H264.
With H264 works.

Thanks for your replay.
