### ISSUE TITLE
How can I add the camera to my lovecale?

### ISSUE THREAD

**Issue by winnertako** [telmomarques/xiaomi-360-1080p-hacks#41]
How can I add the camera to my lovecale?

I've tried this way:

`type: picture-elements
image: /local/testpattern.jpg
elements:
  - type: image
    entity: camera.backyard_camera
    camera_image: camera.backyard_camera
    camera_view: live
    style:
      left: 50%
      top: 50%
      width: 100%
      height: 100%`

But I can't get any image...

**Comment by HepoH3** [comment]
What camera do you use? If you have rtsp stream with h265 codec, it will probably don't work, see this [comment](https://community.home-assistant.io/t/add-support-for-h-265-in-stream-component/205661/16?u=hepoh).
Well currently I stack with the same problem.

**Comment by winnertako** [comment]
Hello @HepoH3. I'm trying to use the xiaomi MJSXJ05CM. Thank you

**Comment by HepoH3** [comment]
> 
> 
> Hello @HepoH3. I'm trying to use the xiaomi MJSXJ05CM. Thank you

So that's the case. We can only wait for the h264 support, cause it's very unlikely that h265 will be supported in browsers.

**Comment by winnertako** [comment]
I've tried again today and it's working fine with this setup:

<img width="626" alt="Screenshot 2020-09-25 at 09 54 07" src="https://user-images.githubusercontent.com/52783790/94248528-82614e80-ff16-11ea-8f53-dc37357cae9b.png">

`- platform: generic
  still_image_url: "/local/testpattern.jpg"
  stream_source: "rtsp://IP_CAMERA:8554/mainstream"
  name: "Stream #1"`

**Comment by thewh1teagle** [comment]
@winnertako 
Can you share configurations files? I want to add it into readme section

**Comment by HepoH3** [comment]
> 
> 
> I've tried again today and it's working fine with this setup:
> 
> <img alt="Screenshot 2020-09-25 at 09 54 07" width="626" src="https://user-images.githubusercontent.com/52783790/94248528-82614e80-ff16-11ea-8f53-dc37357cae9b.png">
> 
> `- platform: generic still_image_url: "/local/testpattern.jpg" stream_source: "rtsp://IP_CAMERA:8554/mainstream" name: "Stream #1"`

Do you just grab files from the archive that been published in discord server and placed them into sdcard, or you following steps from [this discussion](https://github.com/telmomarques/xiaomi-360-1080p-hacks/issues/18)?

**Comment by danergo** [comment]
This would interest me too. you might not have MJSXJ05CM but MJSXJ02CM. Please confirm.
