### ISSUE TITLE
IMILAB 360 hack?

### ISSUE THREAD

**Issue by JeedHome44** [telmomarques/xiaomi-360-1080p-hacks#61]
Hello,

This repository work with IMILAB 360 1080p?

Thank you

**Comment by javierhurtado** [comment]
Hello, Im interested to :)
CMSXJ16A model

**Comment by postai** [comment]
Me too :)

**Comment by Sagittaq2** [comment]
Me too! Some infomation about this model (CMSXJ16A)?

**Comment by dmontes46** [comment]
doest this work with IMILAB A1 ?

**Comment by patsch9** [comment]
+1

**Comment by teras** [comment]
I'm also interested about CMSXJ16A :bowing_man:

**Comment by rogodra** [comment]
Me too! I am interested in the CMSXJ16A model.

**Comment by tonyboss86** [comment]
Hello, i'm interested too, please.

**Comment by lesonquan** [comment]
Me too! for A1 version :))

**Comment by lesonquan** [comment]
Me too! for A1 version :))

**Comment by lesonquan** [comment]
Me too! for A1 version :))
