### ISSUE TITLE
Camera stayed with the yellow led forever

### ISSUE THREAD

**Issue by guiguille** [telmomarques/xiaomi-360-1080p-hacks#68]
When trying to install the firmware with the SD card, camera led stayed yellow and nothing else happened.
After 25min, I shutdown it a tried without the SD card. Still same, so now my camera is useless can't use anymore ?

Anyone has a solution ?

**Comment by Karwail** [comment]
Quel est la version de ta caméra ? (Sous la caméra, pas sur la boîte)

**Comment by guiguille** [comment]
MJSXJ05CM

**Comment by Karwail** [comment]
Tu as brick ta caméra ... J'ai eu même problème (numéro sous la caméra n'est pas la même boîte..)
Il faut maintenant fouiller sur le web pour trouver le firmware de la mjsxj05cm

**Comment by Karwail** [comment]
https://karwail.freeboxos.fr:5001/share/tLAykxjyVWNQvWVo/

Essaye le firmware nommé IPC .... donne moi des nouvelles !!

**Comment by guiguille** [comment]
Merci de ton aide, j'avais pas vu ton 2 eme commentaire! J'ai finalement après mon message, trouvé sur un forum russe obscure un firmware assez ancien mais qui fonctionne! Tout est rentré dans l'ordre 😄
