### ISSUE TITLE
Led stay solid yellow 

### ISSUE THREAD

**Issue by moi22441** [telmomarques/xiaomi-360-1080p-hacks#73]
I have follow the instruction but the led stay solid yellow during 2 hours.
I don't want to unplug the camera because it's wrote "⚠️ Do not power down the camera while flashing!"

What can i do ?

tanks for help

**Comment by moi22441** [comment]
1 Days after the led still yellow :(

**Comment by vkcorp** [comment]
What kind of instructions did you do ?

**Comment by md-ray** [comment]
I have the same issue, during downgrading the firmware. It's been more than 2 hours, so I believe something is stuck

**Comment by telmomarques** [comment]
The only supported camera is MJSXJ02CM. Do not flash any other model, or you will soft brick it.

To recover the camera you need to flash the original firmware again. Check the pinned messages on discord (badge on readme) to get the correct firmware.

**Comment by md-ray** [comment]
Opps, sorry my bad for my stupid mistake. Seems like my model is MJSXJ05CM.
Thanks @telmomarques for quickly pointing out the original firmware page, I'm restoring it now.

**Comment by moi22441** [comment]
Sorry, i have a MJSXJ05CM to, i have restoring it with another firmware
Thanks for your help
