### ISSUE TITLE
camera preview in app is black after installing the custom firmware

### ISSUE THREAD

**Issue by TrueAccelerator** [telmomarques/xiaomi-360-1080p-hacks#89]
After installing the hack, the xiaomi home app preview for the camera shows black screen. The manual recordings always end with 0b of data. However, the automatic cloud recordings work fine and it reacts to manual position controls. Is this intended behaviour?

**Comment by Bestpa** [comment]
This means you bricked your camera, its broken and unfixable.

**Comment by TrueAccelerator** [comment]
I've simply downgraded it as per instructions on the page of the hack and it's working just fine.
