### ISSUE TITLE
Bricked camera during downgrade

### ISSUE THREAD

**Issue by mate71pl** [telmomarques/xiaomi-360-1080p-hacks#92]
Camera MJSXJ05CM bricked during downgrade. 
I've tried different cards, but it's the same every time. I have a CH341A programmer, could someone provide the correct .bin file with a hack or at least with the firmware version 3.4.2_0062?

**Comment by James-Lu-none** [comment]
[QH128A_01.zip](https://github.com/user-attachments/files/15521568/QH128A_01.zip)
this is the binary file i read directly from the rom using CH341A, hope it helps!

**Comment by mate71pl** [comment]
Thanks a lot. I'll try to test it in my next free time!
